title: 每日新闻摘要
baseurl: "/news-digest"
url: "https://pengjunlong.github.io"

# 方案一：使用本地主题
plugins:
  - jekyll-theme-minima
  - jekyll-paginate
  - jekyll-sitemap

paginate: 10
paginate_path: "/news/page:num/"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: false

collections:
  posts:
    output: true
    permalink: /:year/:month/:title/

sass:
  style: compressed

timezone: Asia/Shanghai