title: 每日新闻摘要
baseurl: "/news-digest"
url: "https://pengjunlong.github.io"

remote_theme: pages-themes/hacker@v0.2.0  # 官方维护版本
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

defaults:
  - scope:
      path: ""
    values:
      layout: default
      show_downloads: false  # 隐藏下载按钮

exclude:
  - Gemfile
  - Gemfile.lock

theme_settings:
  repository: ""  # 隐藏GitHub仓库链接