title: 每日新闻摘要
baseurl: "/news-digest"
url: "https://pengjunlong.github.io"

remote_theme: pages-themes/hacker@v0.2.0  # 官方维护版本
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-paginate-v2

pagination:
  enabled: true
  per_page: 5
  collection: 'posts'  # 与集合名称一致
  permalink: "/page/:num/"
  sort_field: "date"
  sort_reverse: true

# 禁用下载按钮
show_downloads: false

# 自定义集合
collections:
  posts:
    output: true
    permalink: /:year/:month/:day/:title/

include:
  - _data        # 包含数据目录
  - subsite-config.json # 包含模板文件

exclude:
  - node_modules
  - vendor
  - Gemfile
  - Gemfile.lock

theme_settings:
  repository: ""  # 隐藏GitHub仓库链接

