title: 每日新闻摘要
baseurl: "/news-digest"
url: "https://pengjunlong.github.io"

remote_theme: pages-themes/hacker@v0.2.0  # 官方维护版本
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-paginate  # 必须显式声明

defaults:
  - scope:
      path: ""
    values:
      layout: default
      show_downloads: false  # 隐藏下载按钮

include:
  - _data        # 包含数据目录
  - subsite-config.json # 包含模板文件

exclude:
  - node_modules
  - vendor
  - Gemfile
  - Gemfile.lock

theme_settings:
  repository: ""  # 隐藏GitHub仓库链接

# 启用分页
paginate: 6  # 每页显示6篇文章
paginate_path: "/page:num/"  # 分页路径格式
collections:
  posts:
    output: true
    permalink: /news/:year/:month/:title/
