name: Jekyll Site Builder

on:
  schedule:
    - cron: '0 13,23 * * *'  # 北京时间21:00和7:00
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai

    steps:
      # 步骤1：检出代码
      - name: Checkout
        uses: actions/checkout@v4

      # 步骤2：设置Python环境（用于新闻抓取）
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 步骤3：运行新闻抓取脚本
      - name: Run News Crawler
        run: |
          pip install requests beautifulsoup4 python-dateutil
          python scripts/news_crawler.py

      # 步骤4：提交新闻源文件
      - name: Commit News Posts
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add _posts/
          git commit -m "Auto Update: News posts" || echo "No changes to commit"
          git push origin main

  github-pages:
    needs: custom-build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    steps:
      - name: Configure Pages
        uses: actions/configure-pages@v3

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: /  # 必须匹配仓库Pages设置中的发布目录

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v2