name: news_crawler

on:
  schedule:
    - cron: '0 13,23 * * *'  # 北京时间21:00和7:00
  workflow_dispatch:

jobs:
  custom-build:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai

    steps:
      # 步骤1：检出代码
      - name: Checkout
        uses: actions/checkout@v4

      # 步骤2：设置Python环境（用于新闻抓取）
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 步骤3：运行新闻抓取脚本
      - name: Run News Crawler
        run: |
          pip install requests beautifulsoup4 python-dateutil
          python scripts/news_crawler.py

      # 步骤4：提交新闻源文件
      - name: Commit News Posts
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add _posts/
          git commit -m "Auto Update: News posts" || echo "No changes to commit"
          git push origin main